apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::705916831084:role/eksctl-eksctl-demo-nodegroup-ng-e-NodeInstanceRole-1X0IHN4T8IRTO
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::705916831084:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-25T09:42:43Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1744"
  uid: ff1b3485-b95e-4a86-9b3a-54559c94bf1c
